version: '3.8'

services:
  app:
    build: ./webapp
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
