name: Python CI/CD with Docker in Webapp Directory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      -
    - name: Run Pytest
      run: |
        pytest

    - name: Build Docker Image in Webapp Directory
      run: |
        cd webapp
        docker build -t webapp .










     
